artifacts/ArtifactHandling/Get-AppFilesSortedByDependencies.ps1
artifacts/ArtifactHandling/Import-Artifacts.ps1
artifacts/ArtifactHandling/Invoke-DownloadArtifact.ps1

- Download TargetFolder Name was not correct
- Logging improved

fix-folder-names

---

artifacts/ArtifactHandling/Import-AppArtifact.ps1
artifacts/ArtifactHandling/Import-Artifacts.ps1
artifacts/ArtifactHandling/Import-FobArtifact.ps1
artifacts/ArtifactHandling/Import-Fonts.ps1
artifacts/ArtifactHandling/Import-RIMArtifact.ps1

Include Duration into AdditionalSetup to provide better information for performance improvements.
related to: https://dev.azure.com/cc-ppi/General/_boards/board/t/General%20Team/Stories/?workitem=419

pref(measurement of durations): Duration information about steps added to output

---

artifacts/ArtifactHandling/Import-AppArtifact.ps1

https://dev.azure.com/cc-ppi/General/_boards/board/t/General%20Team/Stories/?workitem=485

fix(scope parameter was not present in nav2018)

---

artifacts/ArtifactHandling/Import-AppArtifact.ps1

https://dev.azure.com/cc-ppi/General/_boards/board/t/General%20Team/Stories/?workitem=485

fix(scope and tenant parameter are not part of NAV2018 cmdlet)

---

artifacts/ArtifactHandling/Import-AppArtifact.ps1

https://dev.azure.com/cc-ppi/General/_boards/board/t/General%20Team/Stories/?workitem=485

fix(parameter force does not work with nav2018 cmdlet Publish-NAVApp)

---

artifacts/ArtifactHandling/Invoke-DownloadArtifact.ps1

https://dev.azure.com/cc-ppi/General/_workitems/edit/988
#988

fix: specified artifact version was not respected

---

artifacts/ArtifactHandling/Invoke-DownloadArtifact.ps1

fix: version resolution worked incorrect for artifacts. [#1019](https://dev.azure.com/cc-ppi/General/_workitems/edit/1019)

fix: version resolution worked incorrect for artifacts. #1019

---

CHANGELOG.md
artifacts/ArtifactHandling/Add-ArtifactsLog.ps1
artifacts/ArtifactHandling/Import-AppArtifact.ps1

Added a serverity level debug to the logging function due logging compiler errors as error will cause ALOps to cut the log output.

Add severity level debug in logging

---

.vscode/settings.json
CHANGELOG.md
artifacts/ArtifactHandling/Get-PackageVersion.ps1
artifacts/ArtifactHandling/Invoke-DownloadArtifact.ps1

support COSMO IP artifacts (https://dev.azure.com/cc-ppi/General/_workitems/edit/1034)

feat(artifacts): COSMO IP artifacts

---

artifacts/AdditionalSetup.ps1
db-persistence/my/SetupDatabase.ps1

https://dev.azure.com/cc-ppi/General/_workitems/edit/1693

fix(saasbak): move saasbak to volume as well

---

CHANGELOG.md
artifacts/ArtifactHandling/Add-ArtifactsLog.ps1

Suppress configurable errors or warnings changed to Base64
#1730

Suppress configurable errors or warnings changed to Base64

---

artifacts/ArtifactHandling/Import-RIMArtifact.ps1

- Logging for RapidStart import improved. (see [#1830](https://dev.azure.com/cc-ppi/General/_workitems/edit/1830))

Logging for RapidStart 

---

artifacts/ArtifactHandling/Import-RIMArtifact.ps1

- Logging for RapidStart import improved. (see [#1830](https://dev.azure.com/cc-ppi/General/_workitems/edit/1830))

Logging for RapidStart

---

CHANGELOG.md
artifacts/AdditionalSetup.ps1
enable-premium/my/SetupNavUsers.ps1

Change experience at company information for all companies (except 'My Company') into Premium, when `enablePremium` is set to `true`. (see [#1842](https://dev.azure.com/cc-ppi/General/_workitems/edit/1842))

Enable premium

---

artifacts/ArtifactHandling/Get-ArtifactJson.ps1
artifacts/ArtifactHandling/Import-Artifacts.ps1

Apparently searching with Get-ChildItems took almost 1,5 minutes between the publishing of two apps

Performance improvement

---

artifacts/AdditionalSetup.ps1

Co-authored-by: Bert Krätge <bkraetge7094@cosmoconsult.com>

pull master: check if psm exists (#45)

---

artifacts/AdditionalSetup.ps1

Co-authored-by: Bert Krätge <bkraetge7094@cosmoconsult.com>

check if psm exists (#45)

---

CHANGELOG.md
artifacts/AdditionalSetup.ps1
custom-scripts-exec/my/navstart.ps1
health/CheckHealth.ps1

health check not only looks at the BC service, but also considers a marker file

feat(services): Extended health check

---

CHANGELOG.md
artifacts/4PS/Invoke-4PSArtifactHandling.ps1
artifacts/4PS/Unpublish-AllNavAppsInServerInstance.ps1
artifacts/AdditionalSetup.ps1
artifacts/Invoke-AppDeployment.ps1
artifacts/PPIArtifactUtils.psd1
artifacts/PPIArtifactUtils.psm1
db-persistence/my/SetupDatabase.ps1

- Improve stability for corner cases
- Add support for uninstalling all apps as that is required for BC 20 -> 21 updates

feat(upgrade): Stabilize handling, support 20 -> 21

---

artifacts/4PS/Invoke-4PSArtifactHandling.ps1

Updated Initializer app version to latest

Updated Initializer app version to latest

---

artifacts/AdditionalSetupArtifacts.ps1

Adjust import from app-management dll from new location after upgrade to dotnet 6.0 / BC 22

Adjust to new folder structure

---

artifacts/AdditionalSetup.ps1

Adjust import from app-management dll from new location after upgrade to dotnet 6.0 / BC 22

Adjust to new folder structure in BC22

---

artifacts/AdditionalSetup.ps1
db-persistence/my/SetupDatabase.ps1

@tfenster can you please test on your side?

fix(conversion): support multitenant

---

artifacts/Invoke-AppDeployment.ps1

- Allow external downloads (scenario: get a build artifact and install it)
- Run data upgrade if required (scenario: app is published, container is upgraded from 20 to 21 which unpublishes the app, new version is publishes --> then the data upgrade didn't automatically run but is needed before the install)

fix(install): allow download, fix potential issue if data upgrade didn't run
